server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
      - id: pms-route # 商品管理路由
        uri: lb://pms-service
        predicates:
        - Path=/pms/**
      - id: oms-route # 订单管理路由
        uri: lb://oms-service
        predicates:
        - Path=/oms/**
      - id: ums-route # 用户管理路由
        uri: lb://ums-service
        predicates:
        - Path=/ums/**
      - id: wms-route # 仓库管理路由
        uri: lb://wms-service
        predicates:
        - Path=/wms/**
      - id: sms-route # 营销管理路由
        uri: lb://sms-service
        predicates:
        - Path=/sms/**
      - id: auth-route #授权中心
        uri: lb://auth-service
        predicates:
        - Path=/auth/**
#        filters:
#          - RewritePath=/api/(?<segment>.*), /$\{segment}

gmall:
  jwt:
    pubKeyPath: D:\\rsa\\rsa.pub #公钥地址
    cookieName: GMALL_TOKEN #cookie名称